[pytest]

testpaths = tests

pythonpath = .

python_files = test_*.py

addopts =
    -v
    --html=reports/report.html
    --self-contained-html

markers =

    # Application
    application: Tests for QAlchemy application bootstrap, setup and config.
    app_bootstrap: Tests for the application bootstraping.
    work_order: Tests for Work Orders flows.

    # Clients
    client: Test for the AI Client

    # Agents
    agent: Agent related tests
    routing_agent: Unit tests for routing agent.
    requirements_agent: Requirements Agent end-to-end tests

    # Providers
    provider_transformer: Unit tests for transformer provider.

    # Tools
    tools: Tests for tools used by agents

    # Routing
    route: Tests for any routing or route determination that qalchemy is doing.

    # Requirements
    requirements: Requirements capability

    # Logging
    logging: Tests for the QAlchemy logging feature.
    logger_config: Tests for LoggerConfig.
    logger: Tests for Logger.
    log_entry: Tests for LogEntry.
    logger_service: Tests for LoggerService.

    # Reporting
    reporting: Tests for reporting.

    # Mapping
    mapping: Tests for feature mapping for reporting etc.

    # Core Services
    orchestration: Tests for the QAlchemy orchestration feature.
    orchestration_service: Tests for the OrchestrationService component.

    # Features
    feature: Tests for all QAlchemy Features
    generate_code: Tests for generate code service
    review_code:  Tests for review code service