"""
===============================================================================
File Descriptor Header
===============================================================================
File: generated_artifact.py

Purpose:
    Defines the GeneratedArtifact data structure used throughout the
    code generation workflow.

    A GeneratedArtifact represents a single file generated by an AI model,
    including its relative destination path and file contents.

Responsibilities:
    - Store the relative output path.
    - Store the generated file contents.

Design Notes:
    GeneratedArtifact is a lightweight immutable data container used to
    transfer generated artifacts between services.

Dependencies:
    - dataclasses.dataclass

Author:
    Ron Gonzalez

Created:
    July 2026
===============================================================================
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class GeneratedArtifact:
    """
    Represents a single generated project artifact.
    """

    relative_path: str
    content: str
